### 1 

In [1]:
import pandas as pd 
ds = pd.Series([2,4,6])
print(ds)

0    2
1    4
2    6
dtype: int64


### 2

In [5]:
print(type(ds.tolist()))

<class 'list'>


In [6]:
type(ds)

pandas.core.series.Series

In [7]:
ds = ds.tolist()

In [8]:
type(ds)

list

### 3

In [13]:
ds1 = pd.Series([2,3,4])
ds2 = pd.Series([1,2,3])
add = ds1 + ds2 
sub = ds1 - ds2 
mult = ds1 * ds2
div = ds1 / ds2 

print(add, sub, mult, div)

0    3
1    5
2    7
dtype: int64 0    1
1    1
2    1
dtype: int64 0     2
1     6
2    12
dtype: int64 0    2.000000
1    1.500000
2    1.333333
dtype: float64


### 4

In [15]:
ds1 = pd.Series([2,4,6,8,10])
ds2 = pd.Series([1,3,5,7,10])
ds1.compare(ds2)

self  other
0   2.0    1.0
1   4.0    3.0
2   6.0    5.0
3   8.0    7.0

In [16]:
print(ds1==ds2)
print(ds1>ds2)
print(ds1<ds2)

0    False
1    False
2    False
3    False
4     True
dtype: bool
0     True
1     True
2     True
3     True
4    False
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool


### 5

In [17]:
d1 = {'a':100, 'b':200, 'c':300, 'd':400, 'e':800}
print(d1)
new_series = pd.Series(d1)
print(new_series)

{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
a    100
b    200
c    300
d    400
e    800
dtype: int64


### 6

In [21]:
import numpy as np 
ds = np.array([1,2,3])
print(ds)
print(type(ds))
ds1 = pd.Series(ds)
print(ds1)
print(type(ds1))

[1 2 3]
<class 'numpy.ndarray'>
0    1
1    2
2    3
dtype: int64
<class 'pandas.core.series.Series'>


### 7

In [22]:
ds = pd.Series([100,200,'python',300.12,400])
print(ds)

0       100
1       200
2    python
3    300.12
4       400
dtype: object


In [26]:
ds1 = pd.to_numeric(ds, errors="coerce")
print(ds1)

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


In [27]:
ds1 = pd.to_numeric(ds, errors="ignore")
print(ds1)

0       100
1       200
2    python
3    300.12
4       400
dtype: object


### 8

In [36]:
d = {'col1':[1,2,3,4,7,11],'col2':[4,5,6,9,5,0],'col3':[7,5,8,12,1,11]}
df = pd.DataFrame(data=d)
print(df)

   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11


In [39]:
s1 = df.iloc[:,0]
print(s1)
print(type(s1))

0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


In [42]:
s2 = df.loc[:,'col1']
print(s2)
print(type(s2))

0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


### 9

In [46]:
ds = pd.Series([100,200,'python',300.12,400])
print(ds,type(ds))
ar = ds.to_xarray()    #my try
print(ar,type(ar))

0       100
1       200
2    python
3    300.12
4       400
dtype: object <class 'pandas.core.series.Series'>
<xarray.DataArray (index: 5)>
array([100, 200, 'python', 300.12, 400], dtype=object)
Coordinates:
  * index    (index) int64 0 1 2 3 4 <class 'xarray.core.dataarray.DataArray'>


In [47]:
ds = pd.Series([100,200,'python',300.12,400])
print(ds,type(ds))
a = ds.values
print(a,type(a))

0       100
1       200
2    python
3    300.12
4       400
dtype: object <class 'pandas.core.series.Series'>
[100 200 'python' 300.12 400] <class 'numpy.ndarray'>


### 10

In [48]:
series = {'s1':['red','green','white'],'s2':['red', 'black'],'s3':['yellow']}
print(series)

{'s1': ['red', 'green', 'white'], 's2': ['red', 'black'], 's3': ['yellow']}


In [49]:
s1 = pd.Series(series)

In [50]:
print(s1)

s1    [red, green, white]
s2           [red, black]
s3               [yellow]
dtype: object


In [52]:
s2 = s1.apply(pd.Series).stack().reset_index(drop=True)
print(s2)

0       red
1     green
2     white
3       red
4     black
5    yellow
dtype: object


In [53]:
s3 = s1.apply(pd.Series).stack().reset_index(drop=False)
print(s2)

0       red
1     green
2     white
3       red
4     black
5    yellow
dtype: object


In [ ]:
#need to look more at this example 

### 11

In [4]:
ds = pd.Series([100,200,'python',300.12,400])
print(ds)

0       100
1       200
2    python
3    300.12
4       400
dtype: object


In [11]:
ds1 = ds.sort_index()
print(ds1)

0       100
1       200
2    python
3    300.12
4       400
dtype: object


In [9]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
0       100
1       200
3    300.12
4       400
2    python
dtype: object


### 12

In [12]:
print(ds)

0       100
1       200
2    python
3    300.12
4       400
dtype: object


In [13]:
ds_add = pd.Series([500,'php'])
ds1 = pd.concat([ds, ds_add])
print(ds1)

0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


### 13

In [20]:
ds = pd.Series([0,1,2,3,4,5,6,7,8,9,10])
print(ds)
n = 6 
ds1 = ds[ds < n]
print(ds1)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


In [21]:
ds = pd.Series([0,1,2,3,4,5,6,7,8,9,10])
#print(ds)
#n = 6 
ds1 = ds[ds < 6]
print(ds1)

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


### 14

In [22]:
ds = pd.Series(data = [1,2,3], index = ['a','b','c'])
print(ds)
ds1 = ds.reindex(index=['c','a','b'])
print(ds1)

a    1
b    2
c    3
dtype: int64
c    3
a    1
b    2
dtype: int64


### 15

In [26]:
ds = pd.Series([1,2,3,4,5,6,7,8,9,5,3])
mean = ds.mean()
print(mean)
stdev = ds.std()
print(stdev)

4.818181818181818
2.522624895547565


### 16

In [2]:
ds = pd.Series([1,2,3,4,5])
ds1 = pd.Series([2,4,6,8,10])
result = ds[~ds.isin(ds1)]

In [3]:
print(result)

0    1
2    3
4    5
dtype: int64


### 17

In [9]:
import numpy as np
ds00 = pd.Series(np.union1d(ds, ds1))  # union used to find the elements in each series, not including duplicates
ds11 = pd.Series(np.intersect1d(ds, ds1))  # intersect used to find the common numbers of a series
result = ds00[~ds00.isin(ds11)] # ~ used for boolean masking, isin used for finding similar elements

In [10]:
print(ds00,ds11,result)

0     1
1     2
2     3
3     4
4     5
5     6
6     8
7    10
dtype: int64 0    2
1    4
dtype: int64 0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64


In [11]:
result = ds00[ds00.isin(ds11)]  # ~ offers the "not" option, while her only the numbers in both series are given
print(result)

1    2
3    4
dtype: int64


### 18

In [20]:
num_state = np.random.RandomState(100)  #numpy randomstate object creation with seed value 100
num_series = pd.Series(num_state.normal(10,4,20))  # pandas series object with 20 random values, normally distributed, mean 10, std 4
print(num_series)
result = np.percentile(num_series, q=[0,25,50,75,100])  #percentiles of values with q=[min,lower quater,med,upper,max]
print(result)

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]


### 19

In [21]:
num_series = pd.Series(np.take(list('0123456789'), np.random.randint(10, size=40))) #create random series with list of numbers, max 10, 40 items
print("Original Series:")
print(num_series)
print("Frequency of each unique value of the said series.")
result = num_series.value_counts()  #counts frequency of each original character
print(result)

Original Series:
0     8
1     8
2     3
3     4
4     8
5     1
6     7
7     9
8     9
9     0
10    8
11    8
12    5
13    2
14    6
15    6
16    6
17    9
18    5
19    0
20    8
21    2
22    2
23    4
24    6
25    3
26    0
27    1
28    9
29    6
30    1
31    9
32    1
33    5
34    3
35    5
36    7
37    8
38    4
39    7
dtype: object
Frequency of each unique value of the said series.
8    7
9    5
6    5
1    4
5    4
3    3
4    3
7    3
0    3
2    3
dtype: int64


### 20

In [23]:
num_series = pd.Series(np.random.randint(1,5,[15]))
print(num_series)
print("top 2 freq",num_series.value_counts())
result = num_series[~num_series.isin(num_series.value_counts().index[:1])] = 'Other'
print(num_series)

0     2
1     2
2     3
3     4
4     2
5     1
6     4
7     4
8     2
9     3
10    1
11    2
12    1
13    4
14    3
dtype: int64
top 2 freq 2    5
4    4
3    3
1    3
dtype: int64
0         2
1         2
2     Other
3     Other
4         2
5     Other
6     Other
7     Other
8         2
9     Other
10    Other
11        2
12    Other
13    Other
14    Other
dtype: object
